// Date: 10/12/2011 5:54:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX





package rocketScience;

import net.minecraft.src.*;

public class MissilePassengerWarheadModel extends ModelBase
{
      public MissilePassengerWarheadModel()
      {
        New_Shape511 = new ModelRenderer(this, 28, 15);
        New_Shape511.addBox(0F, 0F, 0F, 1, 5, 6);
        New_Shape511.setRotationPoint(-4F, 18F, -3F);
        New_Shape511.rotateAngleX = 0F;
        New_Shape511.rotateAngleY = 0F;
        New_Shape511.rotateAngleZ = 0F;
        New_Shape511.mirror = false;
        New_Shape411 = new ModelRenderer(this, 28, 9);
        New_Shape411.addBox(0F, 0F, 0F, 8, 5, 1);
        New_Shape411.setRotationPoint(-4F, 18F, 3F);
        New_Shape411.rotateAngleX = 0F;
        New_Shape411.rotateAngleY = 0F;
        New_Shape411.rotateAngleZ = 0F;
        New_Shape411.mirror = false;
        New_Shape41 = new ModelRenderer(this, 28, 9);
        New_Shape41.addBox(0F, 0F, 0F, 8, 5, 1);
        New_Shape41.setRotationPoint(-4F, 18F, -4F);
        New_Shape41.rotateAngleX = 0F;
        New_Shape41.rotateAngleY = 0F;
        New_Shape41.rotateAngleZ = 0F;
        New_Shape41.mirror = false;
        New_Shape51 = new ModelRenderer(this, 28, 15);
        New_Shape51.addBox(0F, 0F, 0F, 1, 5, 6);
        New_Shape51.setRotationPoint(3F, 18F, -3F);
        New_Shape51.rotateAngleX = 0F;
        New_Shape51.rotateAngleY = 0F;
        New_Shape51.rotateAngleZ = 0F;
        New_Shape51.mirror = false;
        New_Shape31 = new ModelRenderer(this, 28, 0);
        New_Shape31.addBox(0F, 0F, 0F, 8, 1, 8);
        New_Shape31.setRotationPoint(-4F, 23F, -4F);
        New_Shape31.rotateAngleX = 0F;
        New_Shape31.rotateAngleY = 0F;
        New_Shape31.rotateAngleZ = 0F;
        New_Shape31.mirror = false;
      }

      public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
      {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        New_Shape511.render(f5);
        New_Shape411.render(f5);
        New_Shape41.render(f5);
        New_Shape51.render(f5);
        New_Shape31.render(f5);
      }

      public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
      {
        super.setRotationAngles(f, f1, f2, f3, f4, f5);
      }

      //fields
        ModelRenderer New_Shape511;
        ModelRenderer New_Shape411;
        ModelRenderer New_Shape41;
        ModelRenderer New_Shape51;
        ModelRenderer New_Shape31;
}
