// Date: 10/12/2011 11:20:05 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX





package rocketScience;

import net.minecraft.src.*;

public class ParachuteModel extends ModelBase
{
      public ParachuteModel()
      {
        New_Shape1 = new ModelRenderer(this, 0, 0);
        New_Shape1.addBox(0F, 0F, 0F, 12, 2, 12);
        New_Shape1.setRotationPoint(-6F, 0F, -6F);
        New_Shape1.rotateAngleX = 0F;
        New_Shape1.rotateAngleY = 0F;
        New_Shape1.rotateAngleZ = 0F;
        New_Shape1.mirror = false;
        New_Shape2 = new ModelRenderer(this, 0, 14);
        New_Shape2.addBox(0F, 0F, 0F, 1, 2, 12);
        New_Shape2.setRotationPoint(6F, 2F, -6F);
        New_Shape2.rotateAngleX = 0F;
        New_Shape2.rotateAngleY = 0F;
        New_Shape2.rotateAngleZ = 0F;
        New_Shape2.mirror = false;
        New_Shape21 = new ModelRenderer(this, 0, 14);
        New_Shape21.addBox(0F, 0F, 0F, 1, 2, 12);
        New_Shape21.setRotationPoint(-7F, 2F, -6F);
        New_Shape21.rotateAngleX = 0F;
        New_Shape21.rotateAngleY = 0F;
        New_Shape21.rotateAngleZ = 0F;
        New_Shape21.mirror = false;
        New_Shape22 = new ModelRenderer(this, 0, 14);
        New_Shape22.addBox(0F, 0F, 0F, 1, 2, 12);
        New_Shape22.setRotationPoint(-6F, 2F, 7F);
        New_Shape22.rotateAngleX = 0F;
        New_Shape22.rotateAngleY = 1.58616F;
        New_Shape22.rotateAngleZ = 0F;
        New_Shape22.mirror = false;
        New_Shape221 = new ModelRenderer(this, 0, 14);
        New_Shape221.addBox(0F, 0F, 0F, 1, 2, 12);
        New_Shape221.setRotationPoint(-6F, 2F, -6F);
        New_Shape221.rotateAngleX = 0F;
        New_Shape221.rotateAngleY = 1.5708F;
        New_Shape221.rotateAngleZ = 0F;
        New_Shape221.mirror = false;
        New_Shape3 = new ModelRenderer(this, 26, 14);
        New_Shape3.addBox(0F, 0F, 0F, 8, 1, 1);
        New_Shape3.setRotationPoint(-6F, 4F, -0.5F);
        New_Shape3.rotateAngleX = 0F;
        New_Shape3.rotateAngleY = 0F;
        New_Shape3.rotateAngleZ = 0.7854F;
        New_Shape3.mirror = false;
        New_Shape31 = new ModelRenderer(this, 26, 14);
        New_Shape31.addBox(0F, 0F, 0F, 8, 1, 1);
        New_Shape31.setRotationPoint(-0.5F, 4F, 6F);
        New_Shape31.rotateAngleX = 0;
        New_Shape31.rotateAngleY = 0.7854F*3; //1.5708F;
        New_Shape31.rotateAngleZ = -0.7854F*2F;
        New_Shape31.mirror = false;
        New_Shape311 = new ModelRenderer(this, 26, 14);
        New_Shape311.addBox(0F, 0F, 0F, 8, 1, 1);
        New_Shape311.setRotationPoint(0.5F, 4F, -6F);
        New_Shape311.rotateAngleX = 0F;
        New_Shape311.rotateAngleZ = 0.7854F*2;
        New_Shape311.rotateAngleY = -0.7854F;
        New_Shape311.mirror = false;
        New_Shape312 = new ModelRenderer(this, 26, 14);
        New_Shape312.addBox(0F, 0F, 0F, 8, 1, 1);
        New_Shape312.setRotationPoint(6F, 4F, 0.5F);
        New_Shape312.rotateAngleX = 0F;
        New_Shape312.rotateAngleY = 3.14159F;
        New_Shape312.rotateAngleZ = -0.7854F;
        New_Shape312.mirror = false;
      }

      public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
      {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5);
        New_Shape1.render(f5);
        New_Shape2.render(f5);
        New_Shape21.render(f5);
        New_Shape22.render(f5);
        New_Shape221.render(f5);
        New_Shape3.render(f5);
        New_Shape31.render(f5);
        New_Shape311.render(f5);
        New_Shape312.render(f5);
      }

      public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
      {
        super.setRotationAngles(f, f1, f2, f3, f4, f5);
      }

      //fields
        ModelRenderer New_Shape1;
        ModelRenderer New_Shape2;
        ModelRenderer New_Shape21;
        ModelRenderer New_Shape22;
        ModelRenderer New_Shape221;
        ModelRenderer New_Shape3;
        ModelRenderer New_Shape31;
        ModelRenderer New_Shape311;
        ModelRenderer New_Shape312;
}
